package imgcat

import (
	"encoding/base64"
	"fmt"
	"io"
	"os"
	"strings"
	"testing"
)

func TestWriter(t *testing.T) {
	w := NewWriter(os.Stdout, "20")
	io.Copy(w, base64.NewDecoder(base64.StdEncoding, strings.NewReader(img)))
	w.Close()
	fmt.Println()
}

const img = `/9j/4AAQSkZJRgABAQEASABIAAD/2wBDAAMCAgMCAgMDAwMEAwMEBQgFBQQEBQoHBwYIDAoMDAsKCwsNDhIQDQ4RDgsLEBYQERMUFRUVDA8XGBYUGBIUFRT/2wBDAQMEBAUEBQkFBQkUDQsNFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBT/wAARCAAQABADAREAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAABwEC/8QAIhAAAgICAgICAwAAAAAAAAAAAQMCBAURBhIHEwgjISJC/8QAGQEAAgMBAAAAAAAAAAAAAAAAAgYBBAUH/8QAIxEBAAAGAgEFAQAAAAAAAAAAAQIEESExQQAFAxITFFFxIv/aAAwDAQACEQMRAD8AY/JHzew9DyEMJn+IZXMOt2lIo4uFlfUIbopZ6DIQZJkZRl2lIj9uo6gHfPph8nZQfJYhgbg19JDpphUurWmC2WCGkq+1CImXa7voNU/XmOHfN/E1vJ9HjnH+H5SswtdG/QrWFlaEq2XFqO3RTIRhOW4S/nqewI0Es+XrICZ9cJAXQrRh3bAhcQK4bYmJJp9qIWJw2rXV9n3X9ONXLuOu4TOuuSqVaeP+ulkL6+qHVRsQX79aVOIMQRLW+mxsE6UO66qYkPIkLSDTgTV2xEFkUrSpzSlvNBNf1lcmx3bKLe33R5eM8aHOmsjWrVGtvL9N/IU/sQtBIDIh4iAyco7iIjeu2zrX5rdJ00zP+asbWD70Dm5ZiSoAtK1eFMzEEqVwmDa6tkBvf8Of/9k=`
